### ISSUE TITLE
Prompt to indicate whether features have been selected

### ISSUE THREAD

**Issue by PolarBean** [ilastik/webilastik#12]
One thing I have noticed with new people using ilastik is they often select features, and then move on to the next stage without clicking "OK".  It might be useful to have some kind of either message or other visual indicator to communicate whether OK has been pressed and that it should be pressed to move on to the training stage.

**Comment by Tomaz-Vieira** [comment]
I've seen users doing just that, so it seems like the UI is really misleading them. I thought the orange highlights around the checkboxes would be enough to communicate that, but I'll try to communicate it better =)

**Comment by PolarBean** [comment]
I think this has been solved by recent updates that make features selected by default.
