### ISSUE TITLE
webIlastik resizes itself on open

### ISSUE THREAD

**Issue by PolarBean** [ilastik/webilastik#15]
when i access webilastik via an iframe it resizes itself seemingly to have a vh of 100. This is difficult as it interferes with the workbench layout. Is it possible to change this? else I can probably find a way to handle it on my side but it might be a bit hacky. thank you in advance.

**Comment by Tomaz-Vieira** [comment]
I can change it if need be, but I'm not sure I understand the problem. How is it that webilastik can interfere with the external page if it's running inside an iframe? I expect the `100vh` and `100vw` to just expand to _"100% of the available space in the iframe"_, and the space the iframe is alllowed to occupy is determined by the external page.

**Comment by PolarBean** [comment]
perhaps but not by default. At the moment the iframe exands to take up the page. maybe I can restrict this behaviour somehow. Not a priority, ill look into it and let you know :)

**Comment by PolarBean** [comment]
This is fixed on the workbench side in css :)
