### ISSUE TITLE
Option to set output path directory as a URL parameter

### ISSUE THREAD

**Issue by PolarBean** [ilastik/webilastik#18]

**Comment by Tomaz-Vieira** [comment]
You can now use `output_path_pattern` as a search parameter, which can handle the following replacements strings: 

`{item_index}` ordinal number representing the position of the input data source in the list of inputs 
`{name}` the name of the input datasource (e.g.: the file at '/my/file.png' is named 'file.png'
`{output_type}` the semantic meaning of the data in the output. Either 'simple_segmentation' or 'pixel_probabilities'
`{timestamp}` a string representing the time when the job was submitted (e.g. '2023y12m31d__13h59min58s')
`{extension}` the file (or folder) extension, representing the data type (e.g. 'n5', 'dzi')
