### ISSUE TITLE
Feature Request: Accept Colab Bucket as URL parameter

### ISSUE THREAD

**Issue by PolarBean** [ilastik/webilastik#2]
Thank you for all the recent updates to WebIlastik, the functionality has been improving very quickly. Would it be possible to add support for collab URL parameters. When an app is installed as a Collaboratory app it automatically receives a url paramter every time it is launched by a user (see screenshot). The parameter is clb-collab-id= and it is the current bucket.
 
![Screenshot from 2023-01-26 13-53-09](https://user-images.githubusercontent.com/38996929/214840766-b6fdb0c0-ff97-45bd-aa33-be4cfa801ff2.png)

Would it be possible for WebIlastik to take this parameter and prefill the bucket inputs? This would save the user some time and confusion. Thank you in advance. 

all the best, 

Harry

**Comment by Tomaz-Vieira** [comment]
Hello, Harry. I'm glad you like the new features =)

I think this should be easy to do. I have some questions, though:

1 - Do all collabs come with a bucket ?
2 - Is this `clb-collab-id=` exactly the name of that bucket as seen by the data-proxy or could it be that the bucket has a different name?

**Comment by Tomaz-Vieira** [comment]
Hello,

This is done and deployed now. If you redirect users to the webilastik webapp (currently at https://app.ilastik.org/public/nehuba/index.htm)

then you can also use the query parameter `ebrains_bucket_name` set to the desired bucket name and webilastik will use it as the default bucket name everywhere where it's appropriate.

**Comment by PolarBean** [comment]
Fantastic, thank you. In my testing in both Chrome and Firefox the below link still has the bucket_name prefilled with hbp-image-service. 

https://app.ilastik.org/public/nehuba/index.html?ebrains_bucket_name=space-for-testing-the-nutil-web-applicat#!%7B%22layout%22:%224panel%22%7D

I also tried in a private browsing session so I don't think it is due to my browser cache. Any help with this would be appreciated

**Comment by Tomaz-Vieira** [comment]
Now that I'm re-reading your post I see that the parameter name should actually be `ebrains_bucket_name` so that it matches what you get if webilastik is embedded in the collab, right?

Anyway, I tested with the link you've sent and it seems to be working as expected. Maybe private browsing doesn't drop your cache? Could you try just refreshing with `ctrl + shift + R` ?

**Comment by PolarBean** [comment]
Hey I had tried refreshing with no luck but testing again today and it works perfectly! It's not important for my use case but if you would like to embed the app in the collab then the parameter `clb-collab-id` instead of `ebrains_bucket_name`.

Thanks again!
