### ISSUE TITLE
Chrome wont allow webilastik to login via an iframe

### ISSUE THREAD

**Issue by PolarBean** [ilastik/webilastik#20]
I did some research and it seems like you need to explicitly set samesite to 'Lax' and potentially remove secure.

Heres some more info: https://stackoverflow.com/questions/56828663/how-to-explicitly-set-samesite-none-on-a-flask-response

https://github.com/ilastik/webilastik/blob/c1279d3accf08486e8ffa8924865fbc0e444026e/webilastik/server/session_allocator.py#L106C1-L113
```python
def set_cookie(self, response: web.Response) -> web.Response:
    response.set_cookie(
        name=self.EBRAINS_USER_ACCESS_TOKEN_COOKIE_KEY,
        value=self.user_token.access_token,
        samesite='Lax'
    )
    response.set_cookie(
        name=self.EBRAINS_USER_REFRESH_TOKEN_COOKIE_KEY,
        value=self.user_token.refresh_token,
        samesite='Lax'
    )
    return response
```

**Comment by Tomaz-Vieira** [comment]
Authentication is done via Auth headers now, and I think we've tested it enough in iframes to be sure this is solved =)
