### ISSUE TITLE
Brushing gets stuck if the user scrolls while holding alt

### ISSUE THREAD

**Issue by PolarBean** [ilastik/webilastik#22]
Sometimes after pressing alt the paintbrush remains selected and its not possible to deselect it. Im not sure what causes this. Otherwise it works very well.

**Comment by PolarBean** [comment]
I figured out how to replicate this, if you scroll while holding alt (Im not sure if you also need to be currently actively brushing) the brush will get stuck (at least on my machine).

**Comment by Tomaz-Vieira** [comment]
Thanks! Nice work =)
I'm probably just missing the button release event because the window is losing focus or something. It shouldn't be too hard to fix =)

**Comment by Tomaz-Vieira** [comment]
I was only disabling the brushing mode on the `keyup` event, which could be missed if the users released the `alt` key while the window was out of focus. I'm being a bit more aggressive with the disabling of the brushing mode now, and I can't seem to reproduce it anymore, so I'll mark this as fixed and we can reopen it if we find another case where it's still happening.

**Comment by PolarBean** [comment]
great!
