### ISSUE TITLE
Feature Request: Specify path to ilastik project file as a url parameter

### ISSUE THREAD

**Issue by PolarBean** [ilastik/webilastik#3]
Hi, 

This would be a nice to have feature. I am building a workflow which incorporates webilastik, Since I already know which files I wish to have my user train in ilastik it would be nice if i could direct them to an ilastik session with an ilastik file already open (I will be writing the file for them). If I could specify the path to this file as a URL parameter and have it autoload in webilastik this would be ideal. I understand if this is not in scope. 

all the best,

Harry

**Comment by Tomaz-Vieira** [comment]
Hello,

Yeah, that makes a lot of sense and is the kind of thing I have also proposed to other projects for an easier user experience.

I'm finishing some pressing matters on my side but I figure I can get this done in the near future =)

Thank you for the suggestion!

**Comment by Tomaz-Vieira** [comment]
Hello,

This is done and deployed now. If you redirect users to the webilastik webapp (currently at `https://app.ilastik.org/public/nehuba/index.htm`)

then you can also use the query parameter `project_file_url` set to a uri-encoded url and webilastik will attempt to open it once it manages to create a new session.

**Comment by PolarBean** [comment]
This is fantastic. Thank you for implementing this, I will test it with my app and give you feedback!

**Comment by PolarBean** [comment]
Sorry for the delay in testing. This feature works well. The only issue is that training images do not seem to be saved along with the project file. Perhaps this is the intended behaviour. Other than this I can confirm it works well and am happy for the issue to be closed :) Thank you again for implementing this

**Comment by PolarBean** [comment]
One other issue, It seems like saving a project does not save the bucket name. This is fine, except that it also appears that using the project_file_url parameter also causes webIlastik to ignore clb-collab-id.  I think the expected behaviour would be:
if clb-collab-id is specified use that as the bucket name, else save the bucket name in the project file and use that only if clb-collab-id is unspecified. But other than that, great feature :)
