### ISSUE TITLE
Feature request: active image list selector & coupling segmentation to image

### ISSUE THREAD

**Issue by PolarBean** [ilastik/webilastik#4]
When working with multi image files I notice that by default they are open overlapping one another. Would it be possible to restrict viewing to only image at a time? Related to this, when I select live update and have multiple images open, Ilastik generates many overlapping segmentations for different images (see screenshot). 
![Screenshot from 2023-02-20 10-56-30](https://user-images.githubusercontent.com/38996929/220072893-32ea7c6a-4c83-42de-91d7-823782663a7f.png)

Would it be possible to only show the segmentation of the currently selected image (depending on whether the above request is implemented)? If you would like to reproduce this the bucket name is: _space-for-testing-the-nutil-web-applicat_ and the image folder in the bucket is:  _tg-ArcSwe_mice_precomputed/_
Thank you in advance.

**Comment by Tomaz-Vieira** [comment]
Indeed, that's quite annoying. I'm working on a fix for it, but it clashes a bit with the current architecture. In the meantime, you work around it by opening a new browser tab and rejoining the same session you had already open, keeping a single dataset per browser tab.

**Comment by PolarBean** [comment]
OK I will keep this in mind :) good luck with your fix!

**Comment by Tomaz-Vieira** [comment]
it's up! \o/
Let me know if (when) you find any problems =)

**Comment by PolarBean** [comment]
Fantastic! works perfectly :)
