### ISSUE TITLE
Add license info

### ISSUE THREAD

**Issue by i3v** [ilastik/webilastik#6]
Could you please add the license file?
For now, I just found no license info.

**Comment by Tomaz-Vieira** [comment]
Sure, I'll add one shortly. I still have to go through what the licensing on the dependencies might mean to us, otherwise you can expect the code in this repo itself to be MIT-licensed

**Comment by lzehl** [comment]
@Tomaz-Vieira any update on the matter? (besides a missing license also the copyright (owner and year) are not clear)
