### ISSUE TITLE
Session failed - why?

### ISSUE THREAD

**Issue by sharoncy** [ilastik/webilastik#7]
Hi,

We've been doing some testing of webilastik. Maja and I tried to run sessions in the same collab simultaneously and I got this error message. Did this happen because we tried to run webilastik simultaneously, because we tried to run webilastik within the same collab simultaneously, or for some other reason?  We often use the same demo collab, so it would be good to know what the restrictions are here. Thanks, Sharon. 
![Session_failed](https://user-images.githubusercontent.com/30626642/224707859-240f0316-8989-4a03-b4c9-ad2c5da417d7.PNG)

**Comment by Tomaz-Vieira** [comment]
Hello,

Unless you both were using the same ebrains username, there should be no problem with you both using webilastik at the same time.

It's possible that something went wrong while allocating your session, which made it start in the HPC without the user interface realizing it. It is also possible that something went wrong when you tried to finish your previous session and it was instead left running. 

I'm seeing in the logs that the session with the UUID in your log started around 13:44, some 5 minutes before the first entry in your log. Do you remember trying to start another session before the one from the screenshot?

If something like that happens again, though, you can copy the session UUID that you see in the error log and use it in the "Rejoin Session" field. Alternatively, you can click the "List Sessions" button to check if you have any running sessions, and then either kill them or grab their UUID to rejoin them via the "Rejoin Session" input.

**Comment by Tomaz-Vieira** [comment]
Closing this for now as many things in the session management have changed and it seems quite stable now
