### ISSUE TITLE
Enforce XY layout for 2D images 

### ISSUE THREAD

**Issue by PolarBean** [ilastik/webilastik#8]
WebIlastik is working excellently. While testing I noticed that scrolling is enabled on the bottom left slices panel while the data is 2D. Rather than fix this maybe the top left panel (since it is the only meaningful one for 2D data) could default to full screen if the data is 2D. 
Thank you in advance and good job with all the recent progress!

**Comment by Tomaz-Vieira** [comment]
Good idea =)
I've made it so that viewing 2D images automatically switches to the `xy` layout and disables other view layouts

**Comment by PolarBean** [comment]
Amazing!
